package circularreferencewithoutproxybean.context;

import circularreferencewithoutproxybean.beans.factory.HierarchicalBeanFactory;
import circularreferencewithoutproxybean.beans.factory.ListableBeanFactory;
import circularreferencewithoutproxybean.core.io.ResourceLoader;

public interface ApplicationContext extends ListableBeanFactory, HierarchicalBeanFactory, ResourceLoader {
}
